[flash][pb] Stop building flash.json and flash script
Till today, all the the consumers of flash artifacts should be migrated
to use product bundle V2. Thus we will stop creating flash.json,
flash.sh and build archive (a tgz file that contains fuchsia images and
flash.sh). All the users should use Product bundle as the ONLY standard
product contract.

Note: we have not completely removed the paving flow as some of
consumers have not migrated to flash flow completely.

Run-All-Tests: True
Bug: b/306432796
Change-Id: Id941cb90ab816db55e863dbc802d3cf0e5d6f6ca
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1014014
Reviewed-by: Jay Zhuang <jayzhuang@google.com>
Reviewed-by: Oliver Newman <olivernewman@google.com>
Reviewed-by: Zijie He <zijiehe@google.com>
Reviewed-by: Gordon Tsai <gtsai@google.com>
Reviewed-by: Colin Nelson <colnnelson@google.com>
Commit-Queue: Jiaming Li <lijiaming@google.com>
Reviewed-by: Aidan Wolter <awolter@google.com>
Reviewed-by: Clayton Wilkinson <wilkinsonclay@google.com>

diff --git a/tools/devshell/get-flash-source b/tools/devshell/get-flash-source
--- a/tools/devshell/get-flash-source
+++ b/tools/devshell/get-flash-source
@@ -22,7 +22,6 @@ source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/lib/vars.
 fx-config-read
 
 readonly ARGS_JSON="args.json"
-readonly IMAGES_JSON="images.json"
 readonly PRODUCT_BUNDLES_JSON="product_bundles.json"
 
 build=false
@@ -71,37 +70,23 @@ function _build_gn_label {
   >&2 fx-command-run build "$1"
 }
 
-use_bazel_images_only="$(_query_manifest "${ARGS_JSON}" .use_bazel_images_only)"
-if [[ "${use_bazel_images_only}" == "true" ]]; then
-    main_pb_label="$(_query_manifest "${ARGS_JSON}" .main_pb_label)"
-    if [[ "${main_pb_label}" != "null" ]]; then
-      product_bundle_label="$(_query_manifest "${PRODUCT_BUNDLES_JSON}" ".[] | select(.label | startswith(\"${main_pb_label}\")) | .label")"
-      product_bundle="$(_query_manifest "${PRODUCT_BUNDLES_JSON}" ".[] | select(.label | startswith(\"${main_pb_label}\")) | .path")"
-    else
-      product="$(_query_manifest "${ARGS_JSON}" .build_info_product)"
-      board="$(_query_manifest "${ARGS_JSON}" .build_info_board)"
-      product_bundle_name="${product}.${board}"
-      product_bundle="$(_query_manifest "${PRODUCT_BUNDLES_JSON}" ".[] | select(.name == \"${product_bundle_name}\") | .path")"
-      product_bundle_label="$(_query_manifest "${PRODUCT_BUNDLES_JSON}" ".[] | select(.name == \"${product_bundle_name}\")| .label")"
-      if [[ -z "${product_bundle}" ]]; then
-        fx-error "Failed to find a product bundle."
-        fx-error "Use \"ffx product list\" to see the list of available product bundles then run \"ffx target flash -b <product-bundle>\"."
-        exit 1
-      fi
-    fi
-    if $build ; then
-      _build_gn_label "${product_bundle_label}"
-    fi
-    echo "product-bundle:${product_bundle}"
+main_pb_label="$(_query_manifest "${ARGS_JSON}" .main_pb_label)"
+if [[ "${main_pb_label}" != "null" ]]; then
+  product_bundle_label="$(_query_manifest "${PRODUCT_BUNDLES_JSON}" ".[] | select(.label | startswith(\"${main_pb_label}\")) | .label")"
+  product_bundle="$(_query_manifest "${PRODUCT_BUNDLES_JSON}" ".[] | select(.label | startswith(\"${main_pb_label}\")) | .path")"
 else
-    flash_manifest="$(_query_manifest "${IMAGES_JSON}" '.[] | select(.name == "flash-manifest") | .path')"
-    if [[ -z "${flash_manifest}" ]]; then
-      fx-error "Failed to find a flash manifest"
-      exit 1
-    fi
-    if $build ; then
-      flash_manifest_label="$(_query_manifest "${IMAGES_JSON}" '.[] | select(.name == "flash-manifest") | .label')"
-      _build_gn_label "${flash_manifest_label}"
-    fi
-    echo "flash-manifest:${flash_manifest}"
+  product="$(_query_manifest "${ARGS_JSON}" .build_info_product)"
+  board="$(_query_manifest "${ARGS_JSON}" .build_info_board)"
+  product_bundle_name="${product}.${board}"
+  product_bundle="$(_query_manifest "${PRODUCT_BUNDLES_JSON}" ".[] | select(.name == \"${product_bundle_name}\") | .path")"
+  product_bundle_label="$(_query_manifest "${PRODUCT_BUNDLES_JSON}" ".[] | select(.name == \"${product_bundle_name}\")| .label")"
+  if [[ -z "${product_bundle}" ]]; then
+    fx-error "Failed to find a product bundle."
+    fx-error "Use \"ffx product list\" to see the list of available product bundles then run \"ffx target flash -b <product-bundle>\"."
+    exit 1
+  fi
 fi
+if $build ; then
+  _build_gn_label "${product_bundle_label}"
+fi
+echo "product-bundle:${product_bundle}"
