[fx][rbe] Fix `fx rbe auth`
Generate missing minimal Bazel workspace file `args.json` that
is now expected by `fuchsia_platform_build.bzl` that is run when
the minimal workspace is setup. This fixes the main bug reported
in the associated bug.

+ Make `fx rbe auth` stop after three failed attempts, and
  add some dividing lines in the output to make it easier to
  identify each tentative.

+ Fix a minor typo.

Note that on a workstation in Paris, the command routinely fails
due to timeouts when trying to upload build event traces to
the remote server, the error looks like the following line,
after all tests have passed:

```
ERROR: The Build Event Protocol upload timed out. com.google.common.util.concurrent.TimeoutFuture$TimeoutFutureException: Timed out: NonCancellationPropagatingFuture@782f1788[status=PENDING,
info=[delegate=[SettableFuture@76e8e6fd[status=PENDING]]]]
```

This typically fails on the first two attempts. On the third one
this will either succeed or fail rather randomly. This issue is
not addressed by this CL.

Bug: 423650483
Change-Id: I84af7cc01765c92d0297b4484b532302aa6175c8
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1296044
Fuchsia-Auto-Submit: David Turner <digit@google.com>
Reviewed-by: Jay Zhuang <jayzhuang@google.com>
Reviewed-by: Aaron Wood <aaronwood@google.com>
Commit-Queue: David Turner <digit@google.com>

diff --git a/tools/devshell/rbe b/tools/devshell/rbe
--- a/tools/devshell/rbe
+++ b/tools/devshell/rbe
@@ -213,17 +213,23 @@ function bazel_auth_test() {
   cat <<EOF
 Testing a small remote-enabled bazel build end-to-end.
 If the first build attempt fails, follow the authentication prompts.
-It will retry until success.
+It will retry twice before reporting failure.
 EOF
-  until test_bazel_rbe
-  do
-    echo "If the previous build attempt failed due to authentication, follow the prompts to authenticate."
-    ensure_auth_for_bazel "$@" || {
-      echo "Failed to authenticate for bazel."
-      return 1
-    }
+  for tries in 1 2 3; do
+      printf "\n=== Attempt $tries/3 =====================\n"
+      if test_bazel_rbe; then
+          style::echo --green "bazel+RBE authentication successful"
+          return 0
+      fi
   done
-  style::echo --green "bazel+RBE authentication successful"
+  printf "\n======================================\n"
+  echo "If the previous build attempt failed due to authentication, follow the prompts to authenticate."
+  ensure_auth_for_bazel "$@" || {
+    echo "Failed to authenticate for bazel."
+    return 1
+  }
+  fx-error "Failed to use Bazel RBE for unknown reason! Please contact fuchsia-build-team@ !"
+  return 1
 }
 
 function auth_subcommand() {
