[use][target] Explicitly log default target status
Explicitly log the default target status whenever switching out
directories.

Previously, this would've only been logged if an fx-level default target
has been overridden, but now we'll be more explicit about this
information.

Example: ```
❯ fx use out/core.x64-balanced/
INFO: The default device configured for out/core.x64-balanced/ is "fuchsia-emulator".

❯ FUCHSIA_NODENAME=foo fx use out/core.x64-release/
INFO: The default device configured for out/core.x64-release/ is not set.
WARNING: However, you've overridden this by setting $FUCHSIA_NODENAME="foo".
WARNING: If you want to use leave it unset, please unset the $FUCHSIA_NODENAME environment variable.

WARNING: The build level device is unset, but is overridden by the user level device "bar".
WARNING: Please run `ffx target default unset` to fix this.
```

Bug: 394619603
Change-Id: I34808cb6a62a25e524f362905163ce916e988a79
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1294144
Commit-Queue: Darren Chan <chandarren@google.com>
Reviewed-by: David Murphy <djmurphy@google.com>
Fuchsia-Auto-Submit: Darren Chan <chandarren@google.com>

diff --git a/tools/devshell/use b/tools/devshell/use
--- a/tools/devshell/use
+++ b/tools/devshell/use
@@ -101,6 +101,12 @@ function main {
     fi
   fi
 
+  # Remove trailing slash.
+  # This can potentially lead to the file `out/foo/.device` being written to
+  # when calling `fx set-device` instead `out/foo.device`.
+  # shellcheck disable=SC2001
+  build_dir="$(echo "$build_dir" | sed 's:/*$::')"
+
   if [[ "$build_dir" == /* ]]; then
     local -r full_build_dir="${build_dir}"
   else
@@ -116,28 +122,52 @@ function main {
 
   fx-change-build-dir "${build_dir}"
 
+  # Refresh $FUCHSIA_NODENAME to ensure the below checks will report the correct
+  # error message.
+  if [[ -e "${FUCHSIA_BUILD_DIR}.device" ]]; then
+    FUCHSIA_NODENAME="$(<"${FUCHSIA_BUILD_DIR}.device")"
+  else
+    FUCHSIA_NODENAME=""
+  fi
+
+  # Print the default target status message.
+  # If it's already been printed before, do nothing.
+  has_default_target_status_been_printed="false"
+  function print-default-target-status-once {
+    [[ $has_default_target_status_been_printed == "true" ]] && return
+    out_dir="$(realpath -s --relative-to="$FUCHSIA_DIR" "$FUCHSIA_BUILD_DIR")"
+    if [[ -n "${FUCHSIA_NODENAME}" ]]; then
+      fx-info "The default device for ${out_dir} is \"${FUCHSIA_NODENAME}\"."
+    else
+      fx-info "The default device for ${out_dir} is not set."
+    fi
+    has_default_target_status_been_printed="true"
+  }
+  if [[ -n "${FUCHSIA_NODENAME}" ]]; then
+    print-default-target-status-once
+  fi
+
+  # Check if the user has set a default target via environment variable(s)
+  # which can override default targets set by `fx set-device`.
   function external-default-target-env-warning {
-    fx-warn "The default device configured for ${build_dir} is \"${FUCHSIA_NODENAME}\"."
-    fx-warn "However, you've overriden this by setting ${ENV_VARS}."
-    fx-warn "If you want to use \"${FUCHSIA_NODENAME}\", please unset the ${ENV_VAR_NAMES} environment variable."
+    print-default-target-status-once
+    fx-warn "However, you've overridden this by setting ${ENV_VARS}."
+    if [[ -n "${FUCHSIA_NODENAME}" ]]; then
+      fx-warn "If you want to use \"${FUCHSIA_NODENAME}\", please unset the ${ENV_VAR_NAMES} environment variable."
+    else
+      fx-warn "If you want to use leave it unset, please unset the ${ENV_VAR_NAMES} environment variable."
+    fi
 
     # Add a newline to distinguish this as a separate warning than the potential
     # ffx-related warning below.
     echo >&2
   }
-  if [[ -e "${FUCHSIA_BUILD_DIR}.device" ]]; then
-    # Ensure the below checks will report the correct error message.
-    FUCHSIA_NODENAME="$(<"${FUCHSIA_BUILD_DIR}.device")"
+  fx-if-target-set-by-env external-default-target-env-warning
 
-    # Check if the user has set a default target via environment variable(s)
-    # which can override default targets set by `fx set-device`.
-    fx-if-target-set-by-env external-default-target-env-warning
-
-    # Check if the user has set a default target via `ffx target default set`
-    # which can override default targets set by `fx set-device`.
-    # Ignore the return code since this will just be a warning.
-    fx-check-ffx-default-target || true
-  fi
+  # Check if the user has set a default target via `ffx target default set`
+  # which can override default targets set by `fx set-device`.
+  # Ignore the return code since this will just be a warning.
+  fx-check-ffx-default-target || true
 }
 
 main "$@"
