[devshell] Create add-host-test
Change-Id: I728f437c2b072ccadd93c827f1020f5c0a118bbc
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1145967
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>
Reviewed-by: Clayton Wilkinson <wilkinsonclay@google.com>
Fuchsia-Auto-Submit: Christopher Johnson <crjohns@google.com>

diff --git a/tools/devshell/contrib/add-test b/tools/devshell/contrib/add-test
--- a/tools/devshell/contrib/add-test
+++ b/tools/devshell/contrib/add-test
@@ -6,9 +6,11 @@
 #### CATEGORY=Build
 ### add a GN label to args.gn and regen
 
-## usage: fx add-test //foo/bar //foo/baz
+## usage: fx add-test [--target-list TARGET_LIST] //foo/bar //foo/baz
 ##
-## Adds the labels to `developer_test_labels` and regen.
+## Adds the labels to the given TARGET_LIST and regenerates. If --target-list is not
+## specified, the target is developer_test_labels.
+##
 ## This is useful when `fx test` tells you to add a target to the build,
 ## but you have some custom args set in `args.gn`, so do not want to run
 ## `fx set` to overwrite those args.
@@ -19,6 +21,43 @@ source "$SCRIPT_DIR/../lib/vars.sh" || exit $?
 fx-config-read
 
 set -e
+
+DESTINATION_LABEL="developer_test_labels"
+
+function usage() {
+    echo "fx add-test [--target-list TARGET_LIST] LABELS"
+    echo ""
+    echo "Adds the labels to the given TARGET_LIST and regenerates. If --target-list is not"
+    echo "specified, the target is developer_test_labels."
+    echo ""
+}
+
+if [[ $1 == "--help" ]]; then
+    usage
+    exit 0
+fi
+
+if [[ $# -lt 1 ]]; then
+    usage
+    echo "ERROR: Too few arguments. At least one label is required."
+    exit 1
+fi
+
+if [[ "$1" == "--target-list" ]]; then
+    if [[ $# -lt 2 ]]; then
+        usage
+        echo "ERROR: Missing argument for --target-list"
+        exit 1
+    fi
+    if [[ $# -lt 3 ]]; then
+        usage
+        echo "ERROR: Too few arguments. At least one label is required."
+        exit 1
+    fi
+    DESTINATION_LABEL="$2"
+    shift # past argument
+    shift # past value
+fi
 
 # Cache args in case of typos, bad paths, etc.
 args_gn="${FUCHSIA_BUILD_DIR}/args.gn"
@@ -33,7 +72,7 @@ for arg in "$@"; do
         continue
     fi
     # Append the formatted string to args.gn
-    echo "developer_test_labels += [\"$arg\"]" >> "$args_gn"
+    echo "${DESTINATION_LABEL} += [\"$arg\"]" >> "$args_gn"
 done
 
 echo "Generating Ninja outputs file"
