[qemu] Add error for no kvm
Currently if there is no KVM on the host machine, fx qemu -k will output
the wrong error. It asks you to update permissions which doesn't work if
/dev/kvm doesn't exist.

Change-Id: I392bbbfcea47c538d586f39a0632e9a97348a708
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1273764
Reviewed-by: Travis Geiselbrecht <travisg@google.com>
Commit-Queue: Sage Barreda <sagebarreda@google.com>

diff --git a/zircon/scripts/run-zircon b/zircon/scripts/run-zircon
--- a/zircon/scripts/run-zircon
+++ b/zircon/scripts/run-zircon
@@ -174,6 +174,11 @@ while getopts "a:c:D:gHI:km:nNq:s:t::u:Vz:S:M:h-:" FLAG; do
                 echo "error: KVM option (-k) is only supported on a ${ARCH} host architecture"
                 exit 1
             fi
+            if [[ ! -e "/dev/kvm" ]]; then
+                echo "error: /dev/kvm not found. Virtualisation is not supported."
+                echo
+                exit 1
+            fi
             if [[ ! -w "/dev/kvm" ]]; then
                 echo "To use KVM acceleration, adjust permissions to /dev/kvm using:"
                 echo
