[fx][target] Account for all edge cases in...
...fx {set-device, unset-device, use, -t|--target} w.r.t overriding
fx-level behavior from environment variables and ffx.

PSA: http://shortn/_AhuIP0xwu1

Before vs After: https://diff.googleplex.com/#key=am7CxE0Dkpr5

Changes:
 - Make `fx -t|--target` resilient to $FUCHSIA_DEVICE_ADDR.
 - Add checks for $FUCHSIA_DEVICE_ADDR to
   `fx {set-device, unset-device, use}` and improve message wording.
 - Add checks for $FUCHSIA_NODENAME and $FUCHSIA_DEVICE_ADDR to
   `fx use`.
 - Update ffx default target checks in `fx {set-device, unset-device}`
   to call `ffx target default unset`.
 - Add tests for `fx -t|--target`.
 - Add tests for `fx use`.
 - Improve testing for `fx {set-device, unset-device}`.

Test: fx self-test //tools/devshell/tests/fx-internal/fx_test
Test: fx self-test //tools/devshell/tests/subcommands/fx_use_test
Test: fx self-test //tools/devshell/tests/subcommands/fx_unset_device_test
Test: fx self-test //tools/devshell/tests/subcommands/fx_set_device_test
Fixed: 411484355
Change-Id: I31c4e776249469d789d7f74c596364c9617ba43a
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1260606
Fuchsia-Auto-Submit: Darren Chan <chandarren@google.com>
Reviewed-by: Andrew Davies <awdavies@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>
Reviewed-by: Christopher Johnson <crjohns@google.com>

diff --git a/tools/devshell/tests/fx-internal/ffx_target_list_usage_test b/tools/devshell/tests/fx-internal/ffx_target_list_usage_test
--- a/tools/devshell/tests/fx-internal/ffx_target_list_usage_test
+++ b/tools/devshell/tests/fx-internal/ffx_target_list_usage_test
@@ -52,6 +52,24 @@ expect_args() {
   done
 }
 
+init_fake_ffx() {
+  echo > "${ffx}.mock_errors"
+  cat >"${ffx}.mock_side_effects" <<INPUT
+if [[ \${@: -1} == "get" ]]; then
+  if [[ -n "\$FUCHSIA_DEVICE_ADDR" ]]; then
+    echo "\$FUCHSIA_DEVICE_ADDR"
+  elif [[ -n "\$FUCHSIA_NODENAME" ]]; then
+    echo "\$FUCHSIA_NODENAME"
+  else
+    echo "No default target." >&2
+    echo "If exactly one target is connected, ffx will use that." >&2
+  fi
+else
+  echo "Disallowed command: \$*" >> ${ffx}.mock_errors
+fi
+INPUT
+}
+
 # ensure that set-device invocations of ffx use the proper network flags
 TEST_setdevice() {
   ${fx} set-device >/dev/null 2>&1
@@ -63,13 +81,12 @@ TEST_setdevice() {
 
 # ensure that get-fuchsia-device-addr doesn't try to resolve IPv4 addresses
 TEST_getdeviceaddr_resolved_ipv4_addresses() {
+  init_fake_ffx
   local addrs=("127.0.0.1" "255.255.255.255" "1.0.0.1")
   local counter=1
   for addr in "${addrs[@]}"; do
-    echo "${addr}" > "${ffx}.mock_stdout"
-    BT_EXPECT_EQ "$(${fx} -d "${addr}" get-device-addr)" "${addr}"
-    echo "${addr}:8022" > "${ffx}.mock_stdout"
-    BT_EXPECT_EQ "$(${fx} -d "${addr}:8022" get-device-addr)" "${addr}"
+    BT_EXPECT_EQ "$(${fx} -t "${addr}" get-device-addr)" "${addr}"
+    BT_EXPECT_EQ "$(${fx} -t "${addr}:8022" get-device-addr)" "${addr}"
 
     # default target get is called 4 times
     expect_args "${ffx}.mock_state.${counter}" "target" "default" "get"
@@ -88,11 +105,13 @@ TEST_getdeviceaddr_resolved_ipv4_addresses() {
     ((counter+=1))
     BT_EXPECT_FILE_DOES_NOT_EXIST "${ffx}.mock_state.${counter}"
   done
+  BT_EXPECT_FILE_CONTAINS "${ffx}.mock_errors" ""
 }
 
 # ensure that get-fuchsia-device-addr doesn't try to resolve IPv6 addresses
 # using "fx set-device 'address'"
 TEST_getdeviceaddr_resolved_ipv6_addresses_setdevice() {
+  init_fake_ffx
   local addrs=("1:2:3:4" "1::" "b1::8" "1:2:3:4:5:6::8" \
     "1:2:3:4:5:6::8" "1::7:f8" "1:a2:3:b4:5::7:8" "1:2:3:d4:5e::8" "a1::6:7:8" \
     "1:2:c3:4a::6:7:8f" "1:2:3:4::8" "1::5:6:d7:8" "1:2:3::5:6:7:8" "d1:2:3::8" \
@@ -102,7 +121,6 @@ TEST_getdeviceaddr_resolved_ipv6_addresses_setdevice() {
   local counter=1
   for addr in "${addrs[@]}"; do
     # fx syntax requires that IPv6 address is surrounded by square brackets
-    echo "[${addr}]" > "${ffx}.mock_stdout"
     BT_EXPECT ${fx} set-device "[${addr}]" >/dev/null
     BT_EXPECT_EQ "$(${fx} get-device-addr)" "${addr}"
 
@@ -121,11 +139,13 @@ TEST_getdeviceaddr_resolved_ipv6_addresses_setdevice() {
     ((counter+=1))
     BT_EXPECT_FILE_DOES_NOT_EXIST "${ffx}.mock_state.${counter}"
   done
+  BT_EXPECT_FILE_CONTAINS "${ffx}.mock_errors" ""
 }
 
 # ensure that get-fuchsia-device-addr doesn't try to resolve IPv6 addresses
 # using "fx -t 'address' ..."
 TEST_getdeviceaddr_resolved_ipv6_addresses() {
+  init_fake_ffx
   local addrs=("1:2:3:4" "1::" "b1::8" "1:2:3:4:5:6::8" \
     "1:2:3:4:5:6::8" "1::7:f8" "1:a2:3:b4:5::7:8" "1:2:3:d4:5e::8" "a1::6:7:8" \
     "1:2:c3:4a::6:7:8f" "1:2:3:4::8" "1::5:6:d7:8" "1:2:3::5:6:7:8" "d1:2:3::8" \
@@ -134,7 +154,6 @@ TEST_getdeviceaddr_resolved_ipv6_addresses() {
 
   local counter=1
   for addr in "${addrs[@]}"; do
-    echo "[${addr}]" > "${ffx}.mock_stdout"
     # fx syntax requires that IPv6 address is surrounded by square brackets
     BT_EXPECT_EQ "$(${fx} -t "[${addr}]" get-device-addr)"  "${addr}"
 
@@ -149,6 +168,7 @@ TEST_getdeviceaddr_resolved_ipv6_addresses() {
     ((counter+=1))
     BT_EXPECT_FILE_DOES_NOT_EXIST "${ffx}.mock_state.${counter}"
   done
+  BT_EXPECT_FILE_CONTAINS "${ffx}.mock_errors" ""
 }
 
 # ensure `fx -t` fails if ffx is overridding the default target
diff --git a/tools/devshell/tests/subcommands/fx_cp_test b/tools/devshell/tests/subcommands/fx_cp_test
--- a/tools/devshell/tests/subcommands/fx_cp_test
+++ b/tools/devshell/tests/subcommands/fx_cp_test
@@ -21,11 +21,30 @@ BT_MOCKED_TOOLS=(
 
 declare fx ffx sftp
 
+init_fake_ffx() {
+  echo > "${ffx}_mock_errors"
+  cat >"${ffx}.mock_side_effects" <<INPUT
+if [[ \${@: -1} == "get" || \${@: -1} == "get-ssh-address" ]]; then
+  if [[ -n "\$FUCHSIA_DEVICE_ADDR" ]]; then
+    echo "\$FUCHSIA_DEVICE_ADDR"
+  elif [[ -n "\$FUCHSIA_NODENAME" ]]; then
+    echo "\$FUCHSIA_NODENAME"
+  else
+    echo "No default target." >&2
+    echo "If exactly one target is connected, ffx will use that." >&2
+  fi
+else
+  echo "Disallowed command: \$*" >> "${ffx}_mock_errors"
+fi
+INPUT
+}
+
 BT_SET_UP() {
   source "${BT_TEMP_DIR}/tools/devshell/tests/lib/fuchsia-mock.sh"
   fx="$(btf::setup_fx)"
   sftp="${BT_TEMP_DIR}/tools/devshell/sftp"
   ffx="$(btf::make_installed_hosttools_mock ffx)"
+  init_fake_ffx
   btf::make_mock "${BT_TEMP_DIR}/tools/devshell/host-tool"
   cat > "${BT_TEMP_DIR}/tools/devshell/host-tool.mock_side_effects" <<EOF
     if [[ "\$2" == "ffx" ]]; then
@@ -33,31 +52,30 @@ BT_SET_UP() {
       "${ffx}" "\$@"
     fi
 EOF
-
 }
 
 # ensure that "fx -t ipv4:port cp" calls sftp with expected address and port number
 TEST_cp_ipv4_port() {
-  echo "127.0.0.1:8022" > "${ffx}.mock_stdout"
   BT_EXPECT ${fx} -t "127.0.0.1:8022" cp --to-host /tmp/file_in_fuchsia_target /tmp/file_in_host
   BT_EXPECT btf::does-mock-args-contain "${sftp}.mock_state" "-P" "8022"
   BT_EXPECT btf::does-mock-args-contain "${sftp}.mock_state" "[127.0.0.1]"
+  BT_EXPECT_FILE_CONTAINS "${ffx}_mock_errors" ""
 }
 
 # ensure that "fx -t [ipv6]:port cp" calls sftp with expected address and port number
 TEST_cp_ipv6_port() {
-  echo "[fe80::7:8%eth0]:222" > "${ffx}.mock_stdout"
   BT_EXPECT ${fx} -t "[fe80::7:8%eth0]:222" cp --to-host /tmp/file_in_fuchsia_target /tmp/file_in_host
   BT_EXPECT btf::does-mock-args-contain "${sftp}.mock_state" "-P" "222"
   BT_EXPECT btf::does-mock-args-contain "${sftp}.mock_state" "[fe80::7:8%eth0]"
+  BT_EXPECT_FILE_CONTAINS "${ffx}_mock_errors" ""
 }
 
 # ensure that "fx -t addr cp" calls sftp with expected address and no port number
 TEST_cp_addr() {
-  echo "127.0.0.1" > "${ffx}.mock_stdout"
   BT_EXPECT ${fx} -t "127.0.0.1" cp --to-host /tmp/file_in_fuchsia_target /tmp/file_in_host
   BT_EXPECT btf::does-mock-args-contain "${sftp}.mock_state" "[127.0.0.1]"
   BT_EXPECT btf::does-mock-args-not-contain "${sftp}.mock_state" "-P"
+  BT_EXPECT_FILE_CONTAINS "${ffx}_mock_errors" ""
 }
 
 BT_RUN_TESTS "$@"
diff --git a/tools/devshell/tests/subcommands/fx_klog_test b/tools/devshell/tests/subcommands/fx_klog_test
--- a/tools/devshell/tests/subcommands/fx_klog_test
+++ b/tools/devshell/tests/subcommands/fx_klog_test
@@ -20,29 +20,48 @@ BT_FILE_DEPS=(
 
 declare fx ffx
 
+init_fake_ffx() {
+  echo > "${ffx}_mock_errors"
+  cat >"${ffx}.mock_side_effects" <<INPUT
+if [[ \${@: -1} == "get" ]]; then
+  if [[ -n "\$FUCHSIA_DEVICE_ADDR" ]]; then
+    echo "\$FUCHSIA_DEVICE_ADDR"
+  elif [[ -n "\$FUCHSIA_NODENAME" ]]; then
+    echo "\$FUCHSIA_NODENAME"
+  else
+    echo "No default target." >&2
+    echo "If exactly one target is connected, ffx will use that." >&2
+  fi
+elif [[ \${@: -1} != "symbolize" ]]; then
+  echo "Disallowed command: \$*" >> "${ffx}_mock_errors"
+fi
+INPUT
+}
+
 BT_SET_UP() {
   source "${BT_TEMP_DIR}/tools/devshell/lib/vars.sh"
   source "${BT_TEMP_DIR}/tools/devshell/tests/lib/fuchsia-mock.sh"
   fx="$(btf::setup_fx)"
   fx-config-read
   ffx="$(btf::make_installed_hosttools_mock ffx)"
+  init_fake_ffx
   _loglistener="$(btf::make_installed_hosttools_mock loglistener)"
 }
 
 TEST_klog_raw() {
-  echo "testing" > "${ffx}.mock_stdout"
   BT_EXPECT ${fx} -t "testing" klog --raw
   btf::expect-mock-args "${ffx}.mock_state.1" "target" "default" "get"
   btf::expect-mock-args "${ffx}.mock_state.2" --config fuchsia.analytics.ffx_invoker=fx target default get
 
   BT_EXPECT_FILE_DOES_NOT_EXIST "${ffx}.mock_state.4" \
     "ffx should not have been called 3 times fx klog --raw"
+  BT_EXPECT_FILE_CONTAINS "${ffx}_mock_errors" ""
 }
 
 TEST_klog() {
-  echo "testing" > "${ffx}.mock_stdout"
   BT_EXPECT ${fx} -t "testing" klog
   btf::expect-mock-args "${ffx}.mock_state.3" debug symbolize
+  BT_EXPECT_FILE_CONTAINS "${ffx}_mock_errors" ""
 }
 
 BT_RUN_TESTS "$@"
diff --git a/tools/devshell/tests/subcommands/fx_log_test b/tools/devshell/tests/subcommands/fx_log_test
--- a/tools/devshell/tests/subcommands/fx_log_test
+++ b/tools/devshell/tests/subcommands/fx_log_test
@@ -25,24 +25,41 @@ BT_MOCKED_TOOLS=(
 
 declare fx ffx
 
+init_fake_ffx() {
+  echo > "${ffx}_mock_errors"
+  cat >"${ffx}.mock_side_effects" <<INPUT
+if [[ \${@: -1} == "get" ]]; then
+  if [[ -n "\$FUCHSIA_DEVICE_ADDR" ]]; then
+    echo "\$FUCHSIA_DEVICE_ADDR"
+  elif [[ -n "\$FUCHSIA_NODENAME" ]]; then
+    echo "\$FUCHSIA_NODENAME"
+  else
+    echo "No default target." >&2
+    echo "If exactly one target is connected, ffx will use that." >&2
+  fi
+fi
+INPUT
+}
+
 BT_SET_UP() {
   source "${BT_TEMP_DIR}/tools/devshell/lib/vars.sh"
   source "${BT_TEMP_DIR}/tools/devshell/tests/lib/fuchsia-mock.sh"
   fx="$(btf::setup_fx)"
   fx-config-read
   ffx="$(btf::make_installed_hosttools_mock ffx)"
+  init_fake_ffx
 }
 
 TEST_log_raw() {
-  echo "testing" > "${ffx}.mock_stdout"
   BT_EXPECT ${fx} -t testing log --legacy --raw
   btf::expect-mock-args "${ffx}.mock_state.2" --config fuchsia.analytics.ffx_invoker=fx target default get
+  BT_EXPECT_FILE_CONTAINS "${ffx}_mock_errors" ""
 }
 
 TEST_log() {
-  echo "testing" > "${ffx}.mock_stdout"
   BT_EXPECT ${fx} -t testing log --flag1 --flag2
   btf::expect-mock-args "${ffx}.mock_state.2" log --flag1 --flag2
+  BT_EXPECT_FILE_CONTAINS "${ffx}_mock_errors" ""
 }
 
 BT_RUN_TESTS "$@"
diff --git a/tools/devshell/tests/subcommands/fx_unset_device_test b/tools/devshell/tests/subcommands/fx_unset_device_test
--- a/tools/devshell/tests/subcommands/fx_unset_device_test
+++ b/tools/devshell/tests/subcommands/fx_unset_device_test
@@ -24,6 +24,7 @@ BT_MKDIR_DEPS=(
 BT_SET_UP() {
     source "${BT_TEMP_DIR}/tools/devshell/tests/lib/fuchsia-mock.sh"
     fx="$(btf::setup_fx)"
+    ffx="$(btf::make_installed_hosttools_mock ffx)"
     FUCHSIA_DIR="${BT_TEMP_DIR}"
 }
 
@@ -54,22 +55,222 @@ EOF
 }
 
 # Check that the command fails if used with -t
-TEST_fx-unset-device-fails-with-device-flag() {
+TEST_fx-unset-device-fails-with-target-flag() {
     BT_EXPECT_FAIL ${fx} -t foo unset-device foo 2>/dev/null
 }
 
-# test that we warn the user if the set command will be a noop
-TEST_fx-unset-device-warns-if-nodename-env-var-set-already() {
+# Check that the command doesn't fail if a default target hasn't been set yet.
+TEST_fx-unset-device-if-no-default-set() {
+    local out="${BT_TEMP_DIR}/_fx_set_device_output"
+
+    BT_EXPECT ${fx} unset-device >"$out" 2>&1
+
+    # Check that the output has the right message
+    BT_EXPECT_FILE_CONTAINS "${out}" "The default device has been unset for '${FUCHSIA_DIR}/out/default'"
+}
+
+# Check that we error the user if $FUCHSIA_NODENAME has been set by the user.
+TEST_fx-unset-device-errors-if-nodename-env-var-set-already() {
+    local device_file="${FUCHSIA_DIR}/out/default.device"
+    echo "foo" >"${device_file}"
     local out="${BT_TEMP_DIR}/_fx_set_device_output"
     export FUCHSIA_NODENAME="bar"
 
-    # Do not fail, just warn
+    BT_EXPECT_FAIL ${fx} unset-device >"$out" 2>&1
+
+    # Check that the output has the right message
+    BT_EXPECT_FILE_CONTAINS "${out}" "The default device has been unset for '${FUCHSIA_DIR}/out/default'
+ERROR: However, you've overriden this by setting \$FUCHSIA_NODENAME=\"bar\".
+ERROR: If you want to clear the default device, please unset the \$FUCHSIA_NODENAME environment variable."
+    BT_EXPECT_FILE_DOES_NOT_EXIST ${device_file}
+}
+
+# Check that we error the user if $FUCHSIA_DEVICE_ADDR has been set by the user.
+TEST_fx-unset-device-errors-if-device-addr-env-var-set() {
+    local out="${BT_TEMP_DIR}/_fx_set_device_output"
+    export FUCHSIA_DEVICE_ADDR="bar"
+
+    BT_EXPECT_FAIL ${fx} unset-device >"$out" 2>&1
+
+    # Check that the output has the right message
+    BT_EXPECT_FILE_CONTAINS "${out}" "The default device has been unset for '${FUCHSIA_DIR}/out/default'
+ERROR: However, you've overriden this by setting \$FUCHSIA_DEVICE_ADDR=\"bar\".
+ERROR: If you want to clear the default device, please unset the \$FUCHSIA_DEVICE_ADDR environment variable."
+    BT_EXPECT_FILE_DOES_NOT_EXIST ${device_file}
+}
+
+# Check that we error the user if both $FUCHSIA_NODENAME and
+# $FUCHSIA_DEVICE_ADDR have been set by the user.
+TEST_fx-unset-device-errors-if-both-env-vars-set() {
+    local device_file="${FUCHSIA_DIR}/out/default.device"
+    echo "foo" >"${device_file}"
+    local out="${BT_TEMP_DIR}/_fx_set_device_output"
+    export FUCHSIA_NODENAME="bar"
+    export FUCHSIA_DEVICE_ADDR="baz"
+
+    BT_EXPECT_FAIL ${fx} unset-device >"$out" 2>&1
+
+    # Check that the output has the right message
+    BT_EXPECT_FILE_CONTAINS "${out}" "The default device has been unset for '${FUCHSIA_DIR}/out/default'
+ERROR: However, you've overriden this by setting \$FUCHSIA_NODENAME=\"bar\" and \$FUCHSIA_DEVICE_ADDR=\"baz\".
+ERROR: If you want to clear the default device, please unset the \$FUCHSIA_NODENAME and \$FUCHSIA_DEVICE_ADDR environment variable."
+    BT_EXPECT_FILE_DOES_NOT_EXIST ${device_file}
+}
+
+# fx unset-device should print an warning if ffx hasn't been built yet.
+TEST_fx-unset-device-warns-if-ffx-not-built() {
+    local device_file="${FUCHSIA_DIR}/out/default.device"
+    echo "foo" >"${device_file}"
+    local out="${BT_TEMP_DIR}/_fx_set_device_output"
+
+    rm -f "${ffx}"
     BT_EXPECT ${fx} unset-device >"$out" 2>&1
 
-    # Check that the output contains the text
-    BT_EXPECT_FILE_CONTAINS_SUBSTRING "${out}" "WARNING: FUCHSIA_NODENAME is already set to ${FUCHSIA_NODENAME}"
-    BT_EXPECT_FILE_CONTAINS_SUBSTRING "${out}" "WARNING: Calling fx unset-device will remove the <build-dir>.device file but it will not"
-    BT_EXPECT_FILE_CONTAINS_SUBSTRING "${out}" "unset FUCHSIA_NODENAME meaning that the default target will still be set"
+    # Check that the output has the right message
+    BT_EXPECT_FILE_CONTAINS "${out}" "The default device has been unset for '${FUCHSIA_DIR}/out/default'
+WARNING: ffx not found in build directory, skipping verification that effective target device is unset.
+WARNING: Please run \`ffx target default get\` after the build to confirm."
+    BT_EXPECT_FILE_DOES_NOT_EXIST ${device_file}
+}
+
+# fx unset-device should print an warning if ffx hasn't been built yet, but
+# should still check env vars.
+TEST_fx-unset-device-errors-if-ffx-not-built-with-env() {
+    local device_file="${FUCHSIA_DIR}/out/default.device"
+    echo "foo" >"${device_file}"
+    local out="${BT_TEMP_DIR}/_fx_set_device_output"
+    export FUCHSIA_NODENAME="bar"
+
+    rm -f "${ffx}"
+    BT_EXPECT_FAIL ${fx} unset-device >"$out" 2>&1
+
+    # Check that the output has the right message
+    BT_EXPECT_FILE_CONTAINS "${out}" "The default device has been unset for '${FUCHSIA_DIR}/out/default'
+ERROR: However, you've overriden this by setting \$FUCHSIA_NODENAME=\"bar\".
+ERROR: If you want to clear the default device, please unset the \$FUCHSIA_NODENAME environment variable.
+
+WARNING: ffx not found in build directory, skipping verification that effective target device is unset.
+WARNING: Please run \`ffx target default get\` after the build to confirm."
+    BT_EXPECT_FILE_DOES_NOT_EXIST ${device_file}
+}
+
+# fx unset-device deletes the default device file successfully with a mocked
+# ffx.
+TEST_fx-unset-device-ffx-default-target-unset() {
+    local device_file="${FUCHSIA_DIR}/out/default.device"
+    echo "foo" >"${device_file}"
+    local out="${BT_TEMP_DIR}/_fx_set_device_output"
+
+    echo > "${ffx}.mock_errors"
+    cat >"${ffx}.mock_side_effects" <<INPUT
+if [[ \${@: -1} == "get" ]]; then
+  if [[ -n "\$FUCHSIA_DEVICE_ADDR" ]]; then
+    echo "\$FUCHSIA_DEVICE_ADDR"
+  elif [[ -n "\$FUCHSIA_NODENAME" ]]; then
+    echo "\$FUCHSIA_NODENAME"
+  else
+    echo "No default target." >&2
+    echo "If exactly one target is connected, ffx will use that." >&2
+  fi
+else
+  echo "Disallowed command: \$*" >> ${ffx}.mock_errors
+fi
+INPUT
+    BT_EXPECT ${fx} unset-device >"$out" 2>&1
+
+    # Check that the stdout contains the text
+    BT_EXPECT_FILE_CONTAINS "${out}" "The default device has been unset for '${FUCHSIA_DIR}/out/default'"
+    BT_EXPECT_FILE_CONTAINS "${ffx}.mock_errors" ""
+    BT_EXPECT_FILE_DOES_NOT_EXIST ${device_file}
+}
+
+# fx unset-device should unset any default targets on the ffx level.
+TEST_fx-unset-device-fixes-if-ffx-default-target-set() {
+    local device_file="${FUCHSIA_DIR}/out/default.device"
+    echo "foo" >"${device_file}"
+    local out="${BT_TEMP_DIR}/_fx_set_device_output"
+
+    echo > "${ffx}.mock_errors"
+    touch "${ffx}.configured_target"
+    cat >"${ffx}.mock_side_effects" <<INPUT
+if [[ \${@: -1} == "get" ]]; then
+  if [[ -e "${ffx}.configured_target" ]]; then
+    echo "ffx-default-target"
+  else
+    echo "No default target." >&2
+    echo "If exactly one target is connected, ffx will use that." >&2
+  fi
+elif [[ \${@: -1} == "unset" ]]; then
+  if [[ -n "\$FUCHSIA_DEVICE_ADDR" ]] || [[ -n "\$FUCHSIA_NODENAME" ]]; then
+    echo "TEST FAIL: Unexpected default target unset env vars values: <\$FUCHSIA_DEVICE_ADDR,\$FUCHSIA_NODENAME>" >&2
+  fi
+  echo "<unset stderr should propagate>" >&2
+  if [[ -e "${ffx}.configured_target" ]]; then
+    rm "${ffx}.configured_target"
+  else
+    echo "No default targets to unset." >&2
+  fi
+else
+  echo "Disallowed command: \$*" >> ${ffx}.mock_errors
+fi
+INPUT
+    BT_EXPECT ${fx} unset-device >"$out" 2>&1
+
+    # Check that the output has the right message
+    BT_EXPECT_FILE_CONTAINS "${out}" "The default device has been unset for '${FUCHSIA_DIR}/out/default'
+WARNING: The build level device is unset, but is overridden by the user level device \"ffx-default-target\".
+WARNING: Attempting to fix this by running \`ffx target default unset\`...
+<unset stderr should propagate>"
+    BT_EXPECT_FILE_CONTAINS "${ffx}.mock_errors" ""
+    BT_EXPECT_FILE_DOES_NOT_EXIST "${ffx}.configured_target"
+    BT_EXPECT_FILE_DOES_NOT_EXIST ${device_file}
+}
+
+# fx unset-device should unset any default targets on the ffx level.
+TEST_fx-unset-device-errors-if-ffx-default-target-and-env-set() {
+    local device_file="${FUCHSIA_DIR}/out/default.device"
+    echo "foo" >"${device_file}"
+    local out="${BT_TEMP_DIR}/_fx_set_device_output"
+    export FUCHSIA_NODENAME="bar"
+    export FUCHSIA_DEVICE_ADDR="baz"
+
+    echo > "${ffx}.mock_errors"
+    touch "${ffx}.configured_target"
+    cat >"${ffx}.mock_side_effects" <<INPUT
+if [[ \${@: -1} == "get" ]]; then
+  if [[ -e "${ffx}.configured_target" ]]; then
+    echo "ffx-default-target"
+  else
+    echo "No default target." >&2
+    echo "If exactly one target is connected, ffx will use that." >&2
+  fi
+elif [[ \${@: -1} == "unset" ]]; then
+  if [[ -n "\$FUCHSIA_DEVICE_ADDR" ]] || [[ -n "\$FUCHSIA_NODENAME" ]]; then
+    echo "TEST FAIL: Unexpected default target unset env vars values: <\$FUCHSIA_DEVICE_ADDR,\$FUCHSIA_NODENAME>" >&2
+  fi
+  echo "<unset stderr should propagate>" >&2
+  if [[ -e "${ffx}.configured_target" ]]; then
+    rm "${ffx}.configured_target"
+  else
+    echo "No default targets to unset." >&2
+  fi
+else
+  echo "Disallowed command: \$*" >> ${ffx}.mock_errors
+fi
+INPUT
+    BT_EXPECT_FAIL ${fx} unset-device >"$out" 2>&1
+
+    # Check that the output has the right message
+    BT_EXPECT_FILE_CONTAINS "${out}" "The default device has been unset for '${FUCHSIA_DIR}/out/default'
+ERROR: However, you've overriden this by setting \$FUCHSIA_NODENAME=\"bar\" and \$FUCHSIA_DEVICE_ADDR=\"baz\".
+ERROR: If you want to clear the default device, please unset the \$FUCHSIA_NODENAME and \$FUCHSIA_DEVICE_ADDR environment variable.
+
+WARNING: The build level device is unset, but is overridden by the user level device \"ffx-default-target\".
+WARNING: Attempting to fix this by running \`ffx target default unset\`...
+<unset stderr should propagate>"
+    BT_EXPECT_FILE_CONTAINS "${ffx}.mock_errors" ""
+    BT_EXPECT_FILE_DOES_NOT_EXIST "${ffx}.configured_target"
+    BT_EXPECT_FILE_DOES_NOT_EXIST ${device_file}
 }
 
 BT_RUN_TESTS "$@"
diff --git a/tools/devshell/use b/tools/devshell/use
--- a/tools/devshell/use
+++ b/tools/devshell/use
@@ -107,15 +107,36 @@ function main {
     local -r full_build_dir="${FUCHSIA_DIR}/${build_dir}"
   fi
 
-  if [[ -e "${full_build_dir}/args.gn" ]]; then
-    fx-change-build-dir "${build_dir}"
-    fx-check-default-target
-    exit $?
-  else
+  if [[ ! -e "${full_build_dir}/args.gn" ]]; then
     fx-error "\"${build_dir}\" is not a valid build dir."
-    echo ""
+    echo >&2
     fx-command-help
     exit 1
+  fi
+
+  fx-change-build-dir "${build_dir}"
+
+  function external-default-target-env-warning {
+    fx-warn "The default device configured for ${build_dir} is \"${FUCHSIA_NODENAME}\"."
+    fx-warn "However, you've overriden this by setting ${ENV_VARS}."
+    fx-warn "If you want to use \"${FUCHSIA_NODENAME}\", please unset the ${ENV_VAR_NAMES} environment variable."
+
+    # Add a newline to distinguish this as a separate warning than the potential
+    # ffx-related warning below.
+    echo >&2
+  }
+  if [[ -e "${FUCHSIA_BUILD_DIR}.device" ]]; then
+    # Ensure the below checks will report the correct error message.
+    FUCHSIA_NODENAME="$(<"${FUCHSIA_BUILD_DIR}.device")"
+
+    # Check if the user has set a default target via environment variable(s)
+    # which can override default targets set by `fx set-device`.
+    fx-if-target-set-by-env external-default-target-env-warning
+
+    # Check if the user has set a default target via `ffx target default set`
+    # which can override default targets set by `fx set-device`.
+    # Ignore the return code since this will just be a warning.
+    fx-check-ffx-default-target || true
   fi
 }
 
